title: Phgap
description: Phgap's technique Pool
author: Phgap
logo: /static/img/avatar.png
github: https://github.com/phgap
# about: Freelance developer

baseurl: ""
# url: "http://phgap.cn"

disqus_shortname: phgap
# google_analytics: UA-72862926-1

# share:
#   twitter_username: \#
#   fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
